kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: jterrill
    password:
      from_secret: docker_password
    repo: docker.redshift.ai:5000/joshterrill/apiheartbeat
    registry: docker.redshift.ai:5000
    insecure: true
    auto_tag: true
  when:
    branch:
    - master
    event:
    - push

- name: deploy
  image: appleboy/drone-ssh
  privileged: true
  volumes:
  - name: ssh
    path: /drone/.ssh
  settings:
    host: apiheartbeat.com
    user: ubuntu
    port: 22
    key_path: /drone/.ssh/apiheartbeat.pem
    script:
      - docker pull docker.redshift.ai:5000/joshterrill/apiheartbeat:latest
      - docker stop apiheartbeat
      - docker rm apiheartbeat
      - docker run -d -p 80:80 --env PORT=80 --env NODE_ENV=production --name apiheartbeat --restart unless-stopped docker.redshift.ai:5000/joshterrill/apiheartbeat:latest
      - echo "Successfully restarted docker container"
volumes:
- name: ssh
  host:
    path: /root/.ssh

---

kind: pipeline
name: after

steps:
- name: email
  image: drillster/drone-email
  settings:
    from: joshterrill.dev@gmail.com
    host: smtp.gmail.com
    username: joshterrill.dev@gmail.com
    password:
      from_secret: email_password
    recipients:
      - joshterrill.dev@gmail.com

depends_on:
- default
